### ISSUE TITLE
sample config/whoops.yml

### ISSUE THREAD

**Issue by mattiasarro** [flyingmachine/whoops_rails_logger#1]
Nice work on whoops, Daniel!

To save someone else some searching, whoops docs could be more explicit about config/whoops.yml - (for rails at least) you  need to have per-environment settings:

``` yaml
development:
  host: localhost
  port: 3000
```

(This would enable whoops_rails_logger gem to log to a whoops server that's running on localhost:3000)
